### PR TITLE
20 fix loading example text file issue 16

### LINKED ISSUE #16: Problem loading text file as descibed in example
The docstring of the 'asc' reader states show the follwing example:
```
# Channel: Main
# Width: 10 µm
# Height: 10 µm
# Value units: m
 1.0  2.0  3.0  4.0
 5.0  6.0  7.0  8.0
 9.0 10.0 11.0 12.0
```

When loading this example with this package, there is an error:
```python
In [1]: from SurfaceTopography.IO import open_topography                                                                                                                                

In [2]: open_topography("prj/imtek/data/text_file_example/example-from-docstring.txt")                                                                                                  
/home/michael/miniconda3/envs/surfacetopography/lib/python3.7/site-packages/SurfaceTopography/IO/FromFile.py:363: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  data = np.array(data).T
---------------------------------------------------------------------------
CannotDetectFileFormat                    Traceback (most recent call last)
<ipython-input-2-fe252879ed66> in <module>
----> 1 open_topography("prj/imtek/data/text_file_example/example-from-docstring.txt")

~/miniconda3/envs/surfacetopography/lib/python3.7/site-packages/SurfaceTopography/IO/__init__.py in open_topography(fobj, format, communicator)
    185                     # has to be set back to the top of the file
    186                     fobj.seek(0)
--> 187         raise CannotDetectFileFormat(msg)
    188     else:
    189         if format not in lookup_reader_by_format.keys():

CannotDetectFileFormat: tried AscReader: 
 not enough values to unpack (expected 2, got 1)
```
First I thought that the spaces at the beginning of the lines are a problem, but they are not. 
Probably this is related to #14?

### PR DESCRIPTION
**Pull request by mcrot**
This should fix #16 and #14.

### CODE REVIEW

**Comment by mcrot** [comment]
Yes, this test fails because PR #17 is not merged yet, once that is merged, I merge it into this branch here.

**Comment by mcrot** [comment]
I've added a changelog. Both Travis builds have been successful according to Details link, I don't know why the first is still shown as "Pending".

**Comment by pastewka** [comment]
Can you merge this? If not I should be able to merge with failing CI

**Comment by mcrot** [comment]
@pastewka , no I cannot merge, because the "push" build is shown as failed although all tests are green.
Yes, please merge it, thanks.

**Pull request merged**
