### PR TITLE
BUG: Fixing missing deps in setup.py.

### PR DESCRIPTION
**Pull request by mcrot**
It seems that some more dependencies are needed for `pip install SurfaceTopography` to work.

### CODE REVIEW

**Comment by AntoineSIMTEK** [comment]
but I never really understood what should go there.

**Comment by mcrot** [comment]
> but I never really understood what should go there.

This helped me to understand the difference:
https://stackoverflow.com/questions/43658870/requirements-txt-vs-setup-py

**Comment by mcrot** [comment]
The builds fail for `WITH_MPI=no` for most python interpreters because a derivative is almost zero (10^-16), but the tolerance is
not large enough:
```
E               AssertionError: 
E               Arrays are not equal
E               
E               Mismatched elements: 3 / 3 (100%)
E               Max absolute difference: 8.8817842e-16
E               Max relative difference: inf
E                x: array([-6.661338e-16, -8.881784e-16, -8.881784e-16])
E                y: array([0, 0, 0])
```
What shall we do here? Simply increase the tolerance?

**Comment by AntoineSIMTEK** [comment]
What test is this ? 
I think we should use absolute differences instead of relative differences there.

**Comment by mcrot** [comment]
It's the test `test/test_topography1.py::DetrendedSurfaceTest::test_nonuniform3`.

**Comment by AntoineSIMTEK** [comment]
Ok I look at it

**Comment by mcrot** [comment]
Thanks @AntoineSIMTEK  for the change. Strange, that the error appeared, in my local installation is was ok.

Now it happens in the next line. I'll add the same tolerance..

**Comment by AntoineSIMTEK** [comment]
Ok. somehow the numerical errors differ among python versions.

**Comment by mcrot** [comment]
If this fails now, I'll add the fix also to both remaining lines. So you can wait a bit with approving..

**Pull request merged**
