### PR TITLE
BUG: area_per_pt should be scalar in UniformLineScan

### PR DESCRIPTION
**Pull request by AntoineSIMTEK**

### CODE REVIEW

**Comment by pastewka** [comment]
I don't understand, is pixel size always a tuple?

**Comment by AntoineSIMTEK** [comment]
Yes pixel_size is always a tuple, as nb_grid_pts and physical_sizes

**Comment by pastewka** [comment]
Is that resonable or does it point to a larger problem?

**Review by pastewka — APPROVED** [review]

**Comment by AntoineSIMTEK** [comment]
It is reasonable. I think there are advantages in some functions that the pixel size has always the same type

**Pull request merged**
